FROM ghcr.io/linuxserver/baseimage-alpine:3.18
WORKDIR /home/app/build

ENV SHELL bash
ARG NODE_ENV
ENV NODE_ENV="${NODE_ENV}"
ENV PYTHONUNBUFFERED=1

RUN apk update && apk upgrade

RUN apk add git build-base curl npm nodejs python3 py3-pip 
RUN ln -sf python3 /usr/bin/python

RUN python3 -m pip install --no-cache --upgrade pip wheel setuptools chardet tidal-dl

RUN apk add beets

RUN mkdir -p /home/app/standalone/shared/beets
RUN touch /home/app/standalone/shared/beets/beets-library.blb

RUN npm install -g yarn

COPY . .

EXPOSE 8484
EXPOSE 8585

ENTRYPOINT ["sh", "/home/app/build/docker/run-dev.sh"]
