FROM ghcr.io/linuxserver/baseimage-alpine:3.21
WORKDIR /home/app/build

ENV SHELL bash
ARG NODE_ENV
ENV NODE_ENV="${NODE_ENV}"
ENV PYTHONUNBUFFERED=1

RUN apk update && apk upgrade
RUN apk add npm nodejs py-pip ffmpeg beets

RUN mkdir -p $HOME/.venvs
RUN python3 -m venv $HOME/.venvs
RUN source $HOME/.venvs/bin/activate
ENV PATH="$HOME/.venvs/bin:$PATH"

RUN python -m pip install "tiddl==1.9.3" requests ffmpeg mutagen

RUN mkdir -p /home/app/standalone/shared/beets
RUN touch /home/app/standalone/shared/beets/beets-library.blb
RUN mkdir -p /home/app/standalone/download/incomplete/
RUN npm install -g yarn

COPY . .

EXPOSE 8484
EXPOSE 3000

ENTRYPOINT ["sh", "/home/app/build/docker/run-dev.sh"]
