WORKDIR /home/app/build

ENV SHELL bash
ENV PYTHONUNBUFFERED=1

RUN ln -sf python3 /usr/bin/python

RUN python3 -m pip install --force-reinstall -v "tiddl==1.8.3"

RUN mkdir -p /home/app/standalone/shared/beets
RUN touch /home/app/standalone/shared/beets/beets-library.blb