WORKDIR /home/app/build

ENV SHELL=bash
ENV PYTHONUNBUFFERED=1

RUN mkdir -p $HOME/.venvs
RUN python3 -m venv $HOME/.venvs
RUN source $HOME/.venvs/bin/activate
ENV PATH="$HOME/.venvs/bin:$PATH"

RUN apk add ffmpeg

COPY docker/requirements.txt docker/requirements.txt
RUN python -m pip install -r docker/requirements.txt
