name: ESLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint + Prettier
        run: |
          npm install -g eslint@9.14.0
          npm install @eslint/js@9.14.0
          npm install typescript-eslint@latest
          npm install eslint-plugin-jsx-a11y
          npm install eslint-plugin-react
          npm install eslint-plugin-react-hooks
          npm install eslint-config-prettier
          npm install eslint-plugin-prettier
          npm install eslint-plugin-simple-import-sort
          npm install prettier

      - name: Check code lint and format for API
        run: eslint -c ./api/eslint.config.mjs .

      - name: Check code lint and format for APP
        run: eslint -c ./app/eslint.config.mjs .

      - name: Check code lint and format for E2E
        run: eslint -c ./e2e/eslint.config.mjs .
      