name: ESLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint + Prettier
        run: |
          npm install -g eslint@9.15.0
          npm install @eslint/js@9.15.0
          npm install typescript-eslint@8.15.0
          npm install eslint-plugin-jsx-a11y@6.10.2
          npm install eslint-plugin-react@7.37.2
          npm install eslint-plugin-react-hooks@5.0.0
          npm install eslint-config-prettier@9.1.0
          npm install eslint-plugin-prettier@5.2.1
          npm install eslint-plugin-simple-import-sort@12.1.1
          npm install prettier@3.3.3

      - name: Check code lint and format for API
        run: eslint -c ./api/eslint.config.mjs .

      - name: Check code lint and format for APP
        run: eslint -c ./app/eslint.config.mjs .

      - name: Check code lint and format for E2E
        run: eslint -c ./e2e/eslint.config.mjs .
      