name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
jobs:
  lint:
    name: Run oxlint / oxfmt scanning
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'

      - name: Install deps
        run: |
          yarn install

      - name: Run oxlint
        run: |
          yarn lint

      - name: Run oxfmt
        run: |
          yarn format-check
