name: Yarn-Audit
on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

    - name: Yarn Audit
      uses: pragatheeswarans/yarn-audit-action@f3ab4c055f4b8f1db1b1ae0e32bab690c9050603  # v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        label: 'audit issues'
        paths: |
          .
          api
          app
          e2e